server:
  port: 8103

leon:
  jwt:
    secret: "LeonSecretKeyForJWTInEzPracticeExercises2026IsVeryLongAndComplexNow"
    expiration: 7200000 # 2小时，单位毫秒

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:            # 没有密码留空
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000ms
  application:
    name: AuthModuleServer
  cloud:
    sentinel:
      transport:
        # ??sentinel??????
        dashboard: 127.0.0.1:8077
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import:
      - optional:nacos:AuthModuleServer.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ezpracticeexercises
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.a.entity
  configuration:
    map-underscore-to-camel-case: true

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.a.entity