server:
  port: 8104

spring:
  application:
    name: AuthorizationModuleServer
  cloud:
    sentinel:
      transport:
        # ??sentinel??????
        dashboard: 127.0.0.1:8077
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  config:
    import:
      - optional:nacos:AuthorizationModuleServer.yaml
