server:
  port: 8100

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-route
          # 重点：这里使用 lb (LoadBalance) 前缀加上你的服务名
          uri: lb://UserModuleServer
          predicates:
            - Path=/user/**

  config:
    import: nacos:gateway-module.yaml   # 改成你实际的 Data ID
    nacos:
      config:
        server-addr: 127.0.0.1:8848     # 改成你实际的 Nacos 地址